### ISSUE TITLE
don't have and example to how to use

### ISSUE THREAD

**Issue by labba** [CIFASIS/neural-fuzzer#1]
hi,
i'm trying to use this but it keep failing.. 

command line used:
./neural-fuzzer.py --valid-seeds "path\samples\" seeds "app_path\app @@"

the application take a file path as an input argv (like afl)

after a while getting an issue:

Using Theano backend.
Using ./test-916378050145
corpus length: 0
total chars: 0
set([])
nb sequences: 0
Vectorization...
Build model...
Iteration 0
Epoch 1/1
Traceback (most recent call last):
  File "./neural-fuzzer.py", line 258, in <module>
    model.fit(X, y, batch_size=128, nb_epoch=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 408, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1053, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 812, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

**Comment by gaa-cifasis** [comment]
Hi,

Congratulations, you are the first known user of this tool!. As you said, the instructions and documentation is missing. I'm sorry about it. This tool is still under heavy development and i have to commit and push some new code and examples. I will leave this bug open to let know when it is ready (hopefully i will resume the development soon).

Thanks!

**Comment by labba** [comment]
thanks!

**Comment by gaa-cifasis** [comment]
I updated the code and instructions for the generation. Training will be improved soon!

**Comment by labba** [comment]
thanks for the update i will check it out and will give feedbacks
