### ISSUE TITLE
afl-count missing

### ISSUE THREAD

**Issue by supernothing** [CIFASIS/neural-fuzzer#2]
Getting the following traceback when trying to use neural-fuzzer.py

```
/bin/sh: 1: afl-count: not found
Traceback (most recent call last):
  File "neural-fuzzer.py", line 281, in <module>
    n = aflcount(c, "test")
  File "/code/neural-fuzzer/triage.py", line 60, in aflcount
    out = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
```

I haven't been able to find any reference to afl-count outside of this project. Is this a tool to parse the coverage maps you have yet to release?

**Comment by gaa-cifasis** [comment]
Yeap, i afl-count is just a small script based on afl-cmin. I will resume the development very soon of neural-fuzzer and i will update the missing files as well as improve the code and add pre-trained examples.
